CREATE TABLE "projects" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "title" text NOT NULL,
  "description" text,
  "status" text,
  "purpose" text,
  "project_type_id" int,
  "public_authority_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by" uuid,
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "updated_by" uuid,
  "deleted_at" timestamp
);

CREATE TABLE "project_identifiers" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "identifier_value" text NOT NULL,
  "scheme" varchar(50)
);

CREATE TABLE "project_periods" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "period_type" text NOT NULL,
  "start_date" date,
  "end_date" date,
  "max_extent_date" date,
  "duration_days" integer
);

CREATE TABLE "period_types" (
  "code" text PRIMARY KEY,
  "name_en" text NOT NULL,
  "name_th" text,
  "description" text,
  "sequence" int,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "sector" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "parent_id" int,
  "name_th" varchar NOT NULL,
  "name_en" varchar,
  "category" varchar NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "project_sector" (
  "project_id" uuid,
  "sector_id" int,
  PRIMARY KEY ("project_id", "sector_id")
);

CREATE TABLE "additional_classifications" (
  "id" bigserial PRIMARY KEY,
  "scheme" varchar NOT NULL,
  "code" varchar NOT NULL,
  "description" text,
  "uri" text
);

CREATE TABLE "project_additional_classifications" (
  "project_id" uuid,
  "classification_id" bigint,
  PRIMARY KEY ("project_id", "classification_id")
);

CREATE TABLE "project_related_projects" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "project_id" uuid NOT NULL,
  "relationship_id" text NOT NULL,
  "scheme" text,
  "identifier" text NOT NULL,
  "relationship" text NOT NULL,
  "title" text,
  "uri" text
);

CREATE TABLE "project_locations" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "project_id" uuid NOT NULL,
  "description" text,
  "uri" text,
  "geometry_type" text,
  "geometry_coordinates" jsonb,
  "street_address" text,
  "locality" text,
  "region" text,
  "postal_code" text,
  "country_name" text
);

CREATE TABLE "location_gazetteers" (
  "id" bigserial PRIMARY KEY,
  "location_id" uuid UNIQUE NOT NULL,
  "scheme" text NOT NULL
);

CREATE TABLE "location_gazetteer_identifiers" (
  "id" bigserial PRIMARY KEY,
  "gazetteer_id" bigint NOT NULL,
  "identifier" text NOT NULL
);

CREATE TABLE "project_documents" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "document_type" text,
  "title" text,
  "description" text,
  "url" text,
  "date_published" date,
  "date_modified" date,
  "format" text,
  "language" text,
  "page_start" text,
  "page_end" text,
  "access_details" text,
  "author" text
);

CREATE TABLE "project_budgets" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid UNIQUE NOT NULL,
  "description" text,
  "total_amount" numeric,
  "currency" text,
  "request_date" date,
  "approval_date" date
);

CREATE TABLE "budget_breakdowns" (
  "id" bigserial PRIMARY KEY,
  "budget_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "description" text
);

CREATE TABLE "budget_breakdown_items" (
  "id" bigserial PRIMARY KEY,
  "breakdown_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "description" text,
  "amount" numeric,
  "currency" text,
  "uri" text,
  "period_start_date" date,
  "period_end_date" date,
  "period_max_extent_date" date,
  "period_duration_days" integer,
  "source_party_id" text,
  "source_party_name" text
);

CREATE TABLE "project_finance" (
  "id" bigserial PRIMARY KEY,
  "budget_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "asset_class" text,
  "type" text,
  "concessional" boolean,
  "value_amount" numeric,
  "value_currency" text,
  "source" text,
  "financing_party_id" text,
  "financing_party_name" text,
  "period_start_date" date,
  "period_end_date" date,
  "payment_period_start_date" date,
  "payment_period_end_date" date,
  "interest_rate_margin" numeric,
  "description" text
);

CREATE TABLE "project_cost_measurements" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "measurement_date" date,
  "lifecycle_cost_amount" numeric,
  "lifecycle_cost_currency" text
);

CREATE TABLE "cost_groups" (
  "id" bigserial PRIMARY KEY,
  "cost_measurement_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "category" text
);

CREATE TABLE "cost_items" (
  "id" bigserial PRIMARY KEY,
  "cost_group_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "amount" numeric,
  "currency" text,
  "classification_id" text,
  "classification_scheme" text,
  "classification_description" text
);

CREATE TABLE "project_forecasts" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "title" text,
  "description" text
);

CREATE TABLE "forecast_observations" (
  "id" bigserial PRIMARY KEY,
  "forecast_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "measure" text,
  "notes" text,
  "value_amount" numeric,
  "value_currency" text,
  "period_start_date" date,
  "period_end_date" date,
  "period_max_extent_date" date,
  "period_duration_days" integer,
  "unit_name" text,
  "unit_scheme" text,
  "unit_id" text,
  "unit_uri" text,
  "dimensions" jsonb
);

CREATE TABLE "project_parties" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "name" text,
  "identifier_scheme" text,
  "identifier_value" text,
  "identifier_legal_name_id" int,
  "identifier_uri" text,
  "street_address" text,
  "locality" text,
  "region" text,
  "postal_code" text,
  "country_name" text,
  "contact_name" text,
  "contact_email" text,
  "contact_telephone" text,
  "contact_fax" text,
  "contact_url" text
);

CREATE TABLE "party_additional_identifiers" (
  "id" bigserial PRIMARY KEY,
  "party_id" bigint NOT NULL,
  "scheme" text,
  "identifier" text,
  "legal_name_id" int,
  "uri" text
);

CREATE TABLE "party_roles" (
  "party_id" bigint NOT NULL,
  "role" text NOT NULL,
  PRIMARY KEY ("party_id", "role")
);

CREATE TABLE "party_people" (
  "id" bigserial PRIMARY KEY,
  "party_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "name" text,
  "job_title" text
);

CREATE TABLE "party_beneficial_owners" (
  "id" bigserial PRIMARY KEY,
  "party_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "name" text,
  "email" text,
  "telephone" text,
  "fax_number" text,
  "identifier_scheme" text,
  "identifier_value" text,
  "street_address" text,
  "locality" text,
  "region" text,
  "postal_code" text,
  "country_name" text
);

CREATE TABLE "beneficial_owner_nationalities" (
  "owner_id" bigint NOT NULL,
  "nationality" text NOT NULL,
  PRIMARY KEY ("owner_id", "nationality")
);

CREATE TABLE "party_classifications" (
  "party_id" bigint NOT NULL,
  "scheme" text NOT NULL,
  "classification_id" text NOT NULL,
  PRIMARY KEY ("party_id", "scheme", "classification_id")
);

CREATE TABLE "project_contracting_processes" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "ocid" text,
  "external_reference" text,
  "title" text,
  "description" text,
  "status" text,
  "nature" jsonb,
  "contract_amount" numeric,
  "contract_currency" text,
  "final_amount" numeric,
  "final_currency" text,
  "period_start_date" date,
  "period_end_date" date,
  "period_max_extent_date" date,
  "period_duration_days" integer
);

CREATE TABLE "contracting_tenders" (
  "process_id" bigint PRIMARY KEY,
  "procurement_method" text,
  "procurement_method_details" text,
  "date_published" date,
  "cost_estimate_amount" numeric,
  "cost_estimate_currency" text,
  "number_of_tenderers" integer
);

CREATE TABLE "contracting_tender_tenderers" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "name" text
);

CREATE TABLE "contracting_tender_entities" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "role" text,
  "name" text
);

CREATE TABLE "contracting_tender_sustainability" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "strategies" jsonb
);

CREATE TABLE "contracting_suppliers" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "name" text
);

CREATE TABLE "contracting_documents" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "document_type" text,
  "title" text,
  "description" text,
  "url" text,
  "date_published" date,
  "date_modified" date,
  "format" text,
  "language" text,
  "page_start" text,
  "page_end" text,
  "access_details" text,
  "author" text
);

CREATE TABLE "contracting_modifications" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "date" date,
  "description" text,
  "rationale" text,
  "type" text,
  "release_id" text,
  "old_amount" numeric,
  "old_currency" text,
  "new_amount" numeric,
  "new_currency" text,
  "old_start_date" date,
  "old_end_date" date,
  "new_start_date" date,
  "new_end_date" date
);

CREATE TABLE "contracting_transactions" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "source" text,
  "date" date,
  "amount" numeric,
  "currency" text,
  "payer_name" text,
  "payee_name" text,
  "uri" text
);

CREATE TABLE "contracting_milestones" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "title" text,
  "type" text,
  "description" text,
  "code" text,
  "due_date" date,
  "date_met" date,
  "date_modified" date,
  "status" text,
  "value_amount" numeric,
  "value_currency" text
);

CREATE TABLE "contracting_social" (
  "process_id" bigint PRIMARY KEY,
  "labor_budget_amount" numeric,
  "labor_budget_currency" text,
  "labor_obligations" jsonb,
  "labor_description" text
);

CREATE TABLE "contracting_releases" (
  "id" bigserial PRIMARY KEY,
  "process_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "tag" jsonb,
  "date" date,
  "url" text
);

CREATE TABLE "project_metrics" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "title" text,
  "description" text
);

CREATE TABLE "metric_observations" (
  "id" bigserial PRIMARY KEY,
  "metric_id" bigint NOT NULL,
  "local_id" text NOT NULL,
  "measure" text,
  "notes" text,
  "value_amount" numeric,
  "value_currency" text,
  "period_start_date" date,
  "period_end_date" date,
  "period_max_extent_date" date,
  "period_duration_days" integer,
  "unit_name" text,
  "unit_scheme" text,
  "unit_id" text,
  "unit_uri" text,
  "dimensions" jsonb
);

CREATE TABLE "project_transactions" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "source" text,
  "date" date,
  "amount" numeric,
  "currency" text,
  "payer_id" text,
  "payer_name" text,
  "payee_id" text,
  "payee_name" text,
  "uri" text
);

CREATE TABLE "project_milestones" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "title" text,
  "type" text,
  "description" text,
  "code" text,
  "status" text,
  "due_date" date,
  "date_met" date,
  "date_modified" date,
  "value_amount" numeric,
  "value_currency" text,
  "related_milestone_id" text,
  "related_milestone_title" text
);

CREATE TABLE "project_completion" (
  "project_id" uuid PRIMARY KEY,
  "end_date" date,
  "end_date_details" text,
  "final_scope" text,
  "final_scope_details" text,
  "final_value_amount" numeric,
  "final_value_currency" text
);

CREATE TABLE "project_lobbying_meetings" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "meeting_date" timestamp,
  "number_of_participants" integer,
  "street_address" text,
  "locality" text,
  "region" text,
  "postal_code" text,
  "country_name" text,
  "public_office_job_title" text,
  "public_office_person_name" text,
  "public_office_org_id" text,
  "public_office_org_name" text
);

CREATE TABLE "project_social" (
  "project_id" uuid PRIMARY KEY,
  "in_indigenous_land" boolean,
  "land_compensation_amount" numeric,
  "land_compensation_currency" text,
  "health_safety_material_test_description" text
);

CREATE TABLE "social_health_safety_material_tests" (
  "project_id" uuid NOT NULL,
  "test" text NOT NULL,
  PRIMARY KEY ("project_id", "test")
);

CREATE TABLE "social_consultation_meetings" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "local_id" text NOT NULL,
  "meeting_date" timestamp,
  "number_of_participants" integer,
  "street_address" text,
  "locality" text,
  "region" text,
  "postal_code" text,
  "country_name" text,
  "public_office_job_title" text,
  "public_office_person_name" text,
  "public_office_org_id" text,
  "public_office_org_name" text
);

CREATE TABLE "project_environment" (
  "project_id" uuid PRIMARY KEY,
  "has_impact_assessment" boolean,
  "in_protected_area" boolean,
  "abatement_cost_amount" numeric,
  "abatement_cost_currency" text
);

CREATE TABLE "environment_goals" (
  "project_id" uuid NOT NULL,
  "goal" text NOT NULL,
  PRIMARY KEY ("project_id", "goal")
);

CREATE TABLE "environment_climate_oversight_types" (
  "project_id" uuid NOT NULL,
  "oversight_type" text NOT NULL,
  PRIMARY KEY ("project_id", "oversight_type")
);

CREATE TABLE "environment_conservation_measures" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "type" text,
  "description" text
);

CREATE TABLE "environment_environmental_measures" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "type" text,
  "description" text
);

CREATE TABLE "environment_climate_measures" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "type" text,
  "description" text
);

CREATE TABLE "environment_impact_categories" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "scheme" text,
  "category_id" text
);

CREATE TABLE "project_benefits" (
  "id" bigserial PRIMARY KEY,
  "project_id" uuid NOT NULL,
  "title" text,
  "description" text
);

CREATE TABLE "benefit_beneficiaries" (
  "id" bigserial PRIMARY KEY,
  "benefit_id" bigint NOT NULL,
  "description" text,
  "number_of_people" integer,
  "location_id" uuid
);

CREATE TABLE "project_policy_alignment" (
  "project_id" uuid PRIMARY KEY,
  "description" text
);

CREATE TABLE "project_policy_alignment_policies" (
  "project_id" uuid NOT NULL,
  "policy" text NOT NULL,
  PRIMARY KEY ("project_id", "policy")
);

CREATE TABLE "project_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scheme" varchar,
  "code" varchar NOT NULL,
  "name_th" text,
  "name_en" text,
  "description" text
);

CREATE TABLE "ministry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_th" text NOT NULL,
  "name_en" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "agency" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_th" text NOT NULL,
  "name_en" text,
  "ministry_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "project_asset_lifetime" (
  "project_id" uuid PRIMARY KEY,
  "period_start_date" date,
  "period_end_date" date,
  "period_max_extent_date" date,
  "period_duration_days" integer
);

CREATE TABLE "currencies" (
  "code" varchar(3) PRIMARY KEY,
  "name" text NOT NULL,
  "symbol" text,
  "is_active" boolean DEFAULT true
);

CREATE INDEX ON "projects" ("status");

CREATE INDEX ON "projects" ("project_type_id");

CREATE INDEX ON "projects" ("public_authority_id");

CREATE INDEX ON "projects" ("created_at");

CREATE INDEX ON "projects" ("updated_at");

CREATE INDEX ON "projects" ("deleted_at");

CREATE INDEX ON "project_identifiers" ("project_id");

CREATE UNIQUE INDEX ON "project_identifiers" ("project_id", "scheme");

CREATE INDEX ON "project_identifiers" ("identifier_value");

CREATE UNIQUE INDEX ON "project_periods" ("project_id", "period_type");

CREATE INDEX ON "project_periods" ("project_id");

CREATE INDEX ON "project_periods" ("start_date");

CREATE INDEX ON "project_periods" ("end_date");

CREATE INDEX ON "sector" ("code");

CREATE INDEX ON "sector" ("parent_id");

CREATE INDEX ON "sector" ("category");

CREATE INDEX ON "sector" ("is_active");

CREATE INDEX ON "project_sector" ("sector_id");

CREATE UNIQUE INDEX ON "additional_classifications" ("scheme", "code");

CREATE INDEX ON "project_additional_classifications" ("classification_id");

CREATE UNIQUE INDEX ON "project_related_projects" ("project_id", "relationship_id");

CREATE INDEX ON "project_related_projects" ("project_id");

CREATE INDEX ON "project_locations" ("project_id");

CREATE INDEX ON "location_gazetteers" ("location_id");

CREATE INDEX ON "location_gazetteer_identifiers" ("gazetteer_id");

CREATE INDEX ON "project_documents" ("project_id");

CREATE UNIQUE INDEX ON "project_documents" ("project_id", "local_id");

CREATE INDEX ON "project_documents" ("document_type");

CREATE INDEX ON "project_documents" ("date_published");

CREATE INDEX ON "project_budgets" ("project_id");

CREATE INDEX ON "budget_breakdowns" ("budget_id");

CREATE UNIQUE INDEX ON "budget_breakdowns" ("budget_id", "local_id");

CREATE INDEX ON "budget_breakdown_items" ("breakdown_id");

CREATE UNIQUE INDEX ON "budget_breakdown_items" ("breakdown_id", "local_id");

CREATE INDEX ON "project_finance" ("budget_id");

CREATE UNIQUE INDEX ON "project_finance" ("budget_id", "local_id");

CREATE INDEX ON "project_cost_measurements" ("project_id");

CREATE UNIQUE INDEX ON "project_cost_measurements" ("project_id", "local_id");

CREATE INDEX ON "cost_groups" ("cost_measurement_id");

CREATE UNIQUE INDEX ON "cost_groups" ("cost_measurement_id", "local_id");

CREATE INDEX ON "cost_items" ("cost_group_id");

CREATE UNIQUE INDEX ON "cost_items" ("cost_group_id", "local_id");

CREATE INDEX ON "project_forecasts" ("project_id");

CREATE UNIQUE INDEX ON "project_forecasts" ("project_id", "local_id");

CREATE INDEX ON "forecast_observations" ("forecast_id");

CREATE UNIQUE INDEX ON "forecast_observations" ("forecast_id", "local_id");

CREATE INDEX ON "project_parties" ("project_id");

CREATE UNIQUE INDEX ON "project_parties" ("project_id", "local_id");

CREATE INDEX ON "project_parties" ("name");

CREATE INDEX ON "party_additional_identifiers" ("party_id");

CREATE INDEX ON "party_people" ("party_id");

CREATE UNIQUE INDEX ON "party_people" ("party_id", "local_id");

CREATE INDEX ON "party_beneficial_owners" ("party_id");

CREATE UNIQUE INDEX ON "party_beneficial_owners" ("party_id", "local_id");

CREATE INDEX ON "project_contracting_processes" ("project_id");

CREATE UNIQUE INDEX ON "project_contracting_processes" ("project_id", "local_id");

CREATE INDEX ON "project_contracting_processes" ("status");

CREATE INDEX ON "contracting_tender_tenderers" ("process_id");

CREATE UNIQUE INDEX ON "contracting_tender_tenderers" ("process_id", "local_id");

CREATE INDEX ON "contracting_tender_entities" ("process_id");

CREATE INDEX ON "contracting_tender_sustainability" ("process_id");

CREATE INDEX ON "contracting_suppliers" ("process_id");

CREATE UNIQUE INDEX ON "contracting_suppliers" ("process_id", "local_id");

CREATE INDEX ON "contracting_documents" ("process_id");

CREATE UNIQUE INDEX ON "contracting_documents" ("process_id", "local_id");

CREATE INDEX ON "contracting_modifications" ("process_id");

CREATE UNIQUE INDEX ON "contracting_modifications" ("process_id", "local_id");

CREATE INDEX ON "contracting_transactions" ("process_id");

CREATE UNIQUE INDEX ON "contracting_transactions" ("process_id", "local_id");

CREATE INDEX ON "contracting_transactions" ("date");

CREATE INDEX ON "contracting_milestones" ("process_id");

CREATE UNIQUE INDEX ON "contracting_milestones" ("process_id", "local_id");

CREATE INDEX ON "contracting_milestones" ("status");

CREATE INDEX ON "contracting_milestones" ("due_date");

CREATE INDEX ON "contracting_releases" ("process_id");

CREATE UNIQUE INDEX ON "contracting_releases" ("process_id", "local_id");

CREATE INDEX ON "project_metrics" ("project_id");

CREATE UNIQUE INDEX ON "project_metrics" ("project_id", "local_id");

CREATE INDEX ON "metric_observations" ("metric_id");

CREATE UNIQUE INDEX ON "metric_observations" ("metric_id", "local_id");

CREATE INDEX ON "project_transactions" ("project_id");

CREATE UNIQUE INDEX ON "project_transactions" ("project_id", "local_id");

CREATE INDEX ON "project_transactions" ("date");

CREATE INDEX ON "project_milestones" ("project_id");

CREATE UNIQUE INDEX ON "project_milestones" ("project_id", "local_id");

CREATE INDEX ON "project_milestones" ("status");

CREATE INDEX ON "project_milestones" ("due_date");

CREATE INDEX ON "project_lobbying_meetings" ("project_id");

CREATE UNIQUE INDEX ON "project_lobbying_meetings" ("project_id", "local_id");

CREATE INDEX ON "social_consultation_meetings" ("project_id");

CREATE UNIQUE INDEX ON "social_consultation_meetings" ("project_id", "local_id");

CREATE INDEX ON "environment_conservation_measures" ("project_id");

CREATE INDEX ON "environment_environmental_measures" ("project_id");

CREATE INDEX ON "environment_climate_measures" ("project_id");

CREATE INDEX ON "environment_impact_categories" ("project_id");

CREATE INDEX ON "project_benefits" ("project_id");

CREATE INDEX ON "benefit_beneficiaries" ("benefit_id");

CREATE INDEX ON "benefit_beneficiaries" ("location_id");

CREATE UNIQUE INDEX ON "project_type" ("scheme", "code");

CREATE INDEX ON "project_type" ("code");

CREATE INDEX ON "agency" ("ministry_id");

COMMENT ON TABLE "projects" IS 'Main projects table - OC4IDS compliant';

COMMENT ON TABLE "project_periods" IS 'identification, preparation, implementation, etc.';

COMMENT ON TABLE "period_types" IS 'Codelist for period types';

COMMENT ON TABLE "sector" IS 'Hierarchical: transport -> transport.road';

COMMENT ON TABLE "project_parties" IS 'Optimized: merged 1:1 tables for better performance';

COMMENT ON TABLE "project_contracting_processes" IS 'Optimized: merged 1:1 summary/value/period tables';

COMMENT ON TABLE "project_asset_lifetime" IS 'Expected operational lifetime of infrastructure assets';

COMMENT ON TABLE "currencies" IS 'ISO 4217 currency codes';

ALTER TABLE "projects" ADD FOREIGN KEY ("project_type_id") REFERENCES "project_type" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("public_authority_id") REFERENCES "agency" ("id");

ALTER TABLE "project_identifiers" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_periods" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_periods" ADD FOREIGN KEY ("period_type") REFERENCES "period_types" ("code");

ALTER TABLE "sector" ADD FOREIGN KEY ("parent_id") REFERENCES "sector" ("id");

ALTER TABLE "project_sector" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_sector" ADD FOREIGN KEY ("sector_id") REFERENCES "sector" ("id");

ALTER TABLE "project_additional_classifications" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_additional_classifications" ADD FOREIGN KEY ("classification_id") REFERENCES "additional_classifications" ("id");

ALTER TABLE "project_related_projects" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_locations" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "location_gazetteers" ADD FOREIGN KEY ("location_id") REFERENCES "project_locations" ("id");

ALTER TABLE "location_gazetteer_identifiers" ADD FOREIGN KEY ("gazetteer_id") REFERENCES "location_gazetteers" ("id");

ALTER TABLE "project_documents" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_budgets" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_budgets" ADD FOREIGN KEY ("currency") REFERENCES "currencies" ("code");

ALTER TABLE "budget_breakdowns" ADD FOREIGN KEY ("budget_id") REFERENCES "project_budgets" ("id");

ALTER TABLE "budget_breakdown_items" ADD FOREIGN KEY ("breakdown_id") REFERENCES "budget_breakdowns" ("id");

ALTER TABLE "budget_breakdown_items" ADD FOREIGN KEY ("currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_finance" ADD FOREIGN KEY ("budget_id") REFERENCES "project_budgets" ("id");

ALTER TABLE "project_finance" ADD FOREIGN KEY ("value_currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_cost_measurements" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_cost_measurements" ADD FOREIGN KEY ("lifecycle_cost_currency") REFERENCES "currencies" ("code");

ALTER TABLE "cost_groups" ADD FOREIGN KEY ("cost_measurement_id") REFERENCES "project_cost_measurements" ("id");

ALTER TABLE "cost_items" ADD FOREIGN KEY ("cost_group_id") REFERENCES "cost_groups" ("id");

ALTER TABLE "cost_items" ADD FOREIGN KEY ("currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_forecasts" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "forecast_observations" ADD FOREIGN KEY ("forecast_id") REFERENCES "project_forecasts" ("id");

ALTER TABLE "forecast_observations" ADD FOREIGN KEY ("value_currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_parties" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_parties" ADD FOREIGN KEY ("identifier_legal_name_id") REFERENCES "ministry" ("id");

ALTER TABLE "party_additional_identifiers" ADD FOREIGN KEY ("party_id") REFERENCES "project_parties" ("id");

ALTER TABLE "party_additional_identifiers" ADD FOREIGN KEY ("legal_name_id") REFERENCES "ministry" ("id");

ALTER TABLE "party_roles" ADD FOREIGN KEY ("party_id") REFERENCES "project_parties" ("id");

ALTER TABLE "party_people" ADD FOREIGN KEY ("party_id") REFERENCES "project_parties" ("id");

ALTER TABLE "party_beneficial_owners" ADD FOREIGN KEY ("party_id") REFERENCES "project_parties" ("id");

ALTER TABLE "beneficial_owner_nationalities" ADD FOREIGN KEY ("owner_id") REFERENCES "party_beneficial_owners" ("id");

ALTER TABLE "party_classifications" ADD FOREIGN KEY ("party_id") REFERENCES "project_parties" ("id");

ALTER TABLE "project_contracting_processes" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_contracting_processes" ADD FOREIGN KEY ("contract_currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_contracting_processes" ADD FOREIGN KEY ("final_currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_tenders" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_tenders" ADD FOREIGN KEY ("cost_estimate_currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_tender_tenderers" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_tender_entities" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_tender_sustainability" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_suppliers" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_documents" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_modifications" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_modifications" ADD FOREIGN KEY ("old_currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_modifications" ADD FOREIGN KEY ("new_currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_transactions" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_transactions" ADD FOREIGN KEY ("currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_milestones" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_milestones" ADD FOREIGN KEY ("value_currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_social" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "contracting_social" ADD FOREIGN KEY ("labor_budget_currency") REFERENCES "currencies" ("code");

ALTER TABLE "contracting_releases" ADD FOREIGN KEY ("process_id") REFERENCES "project_contracting_processes" ("id");

ALTER TABLE "project_metrics" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "metric_observations" ADD FOREIGN KEY ("metric_id") REFERENCES "project_metrics" ("id");

ALTER TABLE "metric_observations" ADD FOREIGN KEY ("value_currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_transactions" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_transactions" ADD FOREIGN KEY ("currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_milestones" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_milestones" ADD FOREIGN KEY ("value_currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_completion" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_completion" ADD FOREIGN KEY ("final_value_currency") REFERENCES "currencies" ("code");

ALTER TABLE "project_lobbying_meetings" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_social" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_social" ADD FOREIGN KEY ("land_compensation_currency") REFERENCES "currencies" ("code");

ALTER TABLE "social_health_safety_material_tests" ADD FOREIGN KEY ("project_id") REFERENCES "project_social" ("project_id");

ALTER TABLE "social_consultation_meetings" ADD FOREIGN KEY ("project_id") REFERENCES "project_social" ("project_id");

ALTER TABLE "project_environment" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_environment" ADD FOREIGN KEY ("abatement_cost_currency") REFERENCES "currencies" ("code");

ALTER TABLE "environment_goals" ADD FOREIGN KEY ("project_id") REFERENCES "project_environment" ("project_id");

ALTER TABLE "environment_climate_oversight_types" ADD FOREIGN KEY ("project_id") REFERENCES "project_environment" ("project_id");

ALTER TABLE "environment_conservation_measures" ADD FOREIGN KEY ("project_id") REFERENCES "project_environment" ("project_id");

ALTER TABLE "environment_environmental_measures" ADD FOREIGN KEY ("project_id") REFERENCES "project_environment" ("project_id");

ALTER TABLE "environment_climate_measures" ADD FOREIGN KEY ("project_id") REFERENCES "project_environment" ("project_id");

ALTER TABLE "environment_impact_categories" ADD FOREIGN KEY ("project_id") REFERENCES "project_environment" ("project_id");

ALTER TABLE "project_benefits" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "benefit_beneficiaries" ADD FOREIGN KEY ("benefit_id") REFERENCES "project_benefits" ("id");

ALTER TABLE "benefit_beneficiaries" ADD FOREIGN KEY ("location_id") REFERENCES "project_locations" ("id");

ALTER TABLE "project_policy_alignment" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_policy_alignment_policies" ADD FOREIGN KEY ("project_id") REFERENCES "project_policy_alignment" ("project_id");

ALTER TABLE "agency" ADD FOREIGN KEY ("ministry_id") REFERENCES "ministry" ("id");

ALTER TABLE "project_asset_lifetime" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_asset_lifetime" ADD FOREIGN KEY ("project_id") REFERENCES "project_asset_lifetime" ("period_start_date");
