CREATE TABLE projects (
    id TEXT PRIMARY KEY,
    identifiers JSONB,
    updated TIMESTAMP,
    title TEXT,
    description TEXT,
    status TEXT,
    period JSONB,
    identificationPeriod JSONB,
    preparationPeriod JSONB,
    implementationPeriod JSONB,
    completionPeriod JSONB,
    maintenancePeriod JSONB,
    decommissioningPeriod JSONB,
    sector JSONB,
    purpose TEXT,
    additionalClassifications JSONB,
    type JSONB,
    relatedProjects JSONB,
    assetLifetime JSONB,
    locations JSONB,
    budget JSONB,
    costMeasurements JSONB,
    forecasts JSONB,
    parties JSONB,
    publicAuthority JSONB,
    documents JSONB,
    contractingProcesses JSONB,
    metrics JSONB,
    transactions JSONB,
    milestones JSONB,
    completion JSONB,
    lobbyingMeetings JSONB,
    social JSONB,
    environment JSONB,
    benefits JSONB,
    policyAlignment JSONB
);
