from locust import HttpUser, task, between
import random
import json

class OC4IDSUser(HttpUser):
    wait_time = between(1, 3)

    def on_start(self):
        """Called when a User starts."""
        self.project_ids = []
        self.create_project()

    @task(3)
    def get_projects(self):
        """Task to get all projects."""
        self.client.get("/api/v1/datasets?page=1&page_size=10")

    @task(1)
    def create_project(self):
        """Task to create a new project."""
        payload = {
            "title": f"Load Test Project {random.randint(1, 10000)}",
            "description": "Generated by Locust",
            "status": "active"
        }
        # post returns a Response object
        with self.client.post("/api/v1/datasets", json=payload, catch_response=True) as response:
            if response.status_code == 200:
                try:
                    data = response.json()
                    # Response structure: {"message": "...", "project": {"id": "...", ...}}
                    if "project" in data and "id" in data["project"]:
                        self.project_ids.append(data["project"]["id"])
                except Exception as e:
                    response.failure(f"JSON Decode Error: {e}")
            else:
                response.failure(f"Status code: {response.status_code}")

    @task(5)
    def get_single_project(self):
        """Task to get a specific project."""
        if self.project_ids:
            project_id = random.choice(self.project_ids)
            with self.client.get(f"/api/v1/datasets/{project_id}", catch_response=True) as response:
                if response.status_code == 404:
                    # If deleted or not found, remove from list to verify behavior later
                    if project_id in self.project_ids:
                        self.project_ids.remove(project_id)
