# oc4ids_datastore_api/models/__init__.py
# Re-export everything from sub-modules so existing imports still work.

from oc4ids_datastore_api.models.reference import (
    ProjectType,
    Ministry,
    Agency,
    PeriodType,
    Sector,
    Currency,
    AdditionalClassification,
)
from oc4ids_datastore_api.models.project import (
    # Link tables
    ProjectSectorLink,
    ProjectAdditionalClassificationLink,
    # Child tables
    ProjectIdentifier,
    ProjectPeriod,
    ProjectLocation,
    ProjectDocument,
    ProjectBudget,
    BudgetBreakdown,
    BudgetBreakdownItem,
    ProjectFinance,
    ProjectParty,
    PartyAdditionalIdentifier,
    PartyRole,
    PartyPerson,
    PartyBeneficialOwner,
    BeneficialOwnerNationality,
    PartyClassification,
    ProjectContractingProcess,
    ContractingProcessMilestone,
    ContractingTender,
    ContractingTenderTenderer,
    ContractingTenderEntity,
    ContractingTenderSustainability,
    ContractingSupplier,
    ContractingSocial,
    ContractingRelease,
    ContractingProcessTransaction,
    ContractingProcessModification,
    ContractingProcessDocument,
    ProjectRelatedProject,
    ProjectCostMeasurement,
    CostGroup,
    CostItem,
    ProjectForecast,
    ForecastObservation,
    ProjectMetric,
    MetricObservation,
    LocationGazetteer,
    LocationGazetteerIdentifier,
    ProjectLobbyingMeeting,
    ProjectPolicyAlignment,
    ProjectPolicyAlignmentPolicy,
    ProjectAssetLifetime,
    ProjectSocial,
    SocialConsultationMeeting,
    SocialHealthSafetyMaterialTest,
    ProjectEnvironment,
    EnvironmentGoal,
    EnvironmentClimateOversightType,
    EnvironmentConservationMeasure,
    EnvironmentEnvironmentalMeasure,
    EnvironmentClimateMeasure,
    EnvironmentImpactCategory,
    ProjectBenefit,
    BenefitBeneficiary,
    ProjectCompletion,
    # Root project model
    Project,
)
from oc4ids_datastore_api.models.risk import (
    RiskCategory,
    RiskFactor,
    Risk,
    Mitigation,
    Impact,
    RiskCategoryAssignment,
    CategoryFactorLink,
    RiskFactorAssignment,
    RiskCategoryFactorAssignment,
    RiskSource,
    RiskPhase,
    RiskPattern,
)

__all__ = [
    # reference
    "ProjectType", "Ministry", "Agency", "PeriodType", "Sector", "Currency",
    "AdditionalClassification",
    # project link tables
    "ProjectSectorLink", "ProjectAdditionalClassificationLink",
    # project children
    "ProjectIdentifier", "ProjectPeriod", "ProjectLocation", "ProjectDocument",
    "ProjectBudget", "BudgetBreakdown", "BudgetBreakdownItem", "ProjectFinance",
    "ProjectParty", "PartyAdditionalIdentifier", "PartyRole", "PartyPerson",
    "PartyBeneficialOwner", "BeneficialOwnerNationality", "PartyClassification",
    "ProjectContractingProcess", "ContractingProcessMilestone", "ContractingTender",
    "ContractingTenderTenderer", "ContractingTenderEntity", "ContractingTenderSustainability",
    "ContractingSupplier", "ContractingSocial", "ContractingRelease",
    "ContractingProcessTransaction", "ContractingProcessModification",
    "ContractingProcessDocument", "ProjectRelatedProject",
    "ProjectCostMeasurement", "CostGroup", "CostItem",
    "ProjectForecast", "ForecastObservation",
    "ProjectMetric", "MetricObservation",
    "LocationGazetteer", "LocationGazetteerIdentifier",
    "ProjectLobbyingMeeting", "ProjectPolicyAlignment", "ProjectPolicyAlignmentPolicy",
    "ProjectAssetLifetime",
    "ProjectSocial", "SocialConsultationMeeting", "SocialHealthSafetyMaterialTest",
    "ProjectEnvironment", "EnvironmentGoal", "EnvironmentClimateOversightType",
    "EnvironmentConservationMeasure", "EnvironmentEnvironmentalMeasure",
    "EnvironmentClimateMeasure", "EnvironmentImpactCategory",
    "ProjectBenefit", "BenefitBeneficiary", "ProjectCompletion",
    "Project",
    # risk
    "RiskCategory", "RiskFactor", "Risk", "Mitigation", "Impact",
    "RiskCategoryAssignment", "CategoryFactorLink", "RiskFactorAssignment",
    "RiskCategoryFactorAssignment",
    "RiskSource", "RiskPhase", "RiskPattern",
]
